@TicketSystem.API_HostAddress = https://localhost:7013
@token = CfDJ8ET3kv6KW-NArwbm-mk0POZye2dLRMucJKUhhh8v9rhoYNQiYRRa0q80y5miQT9uo0AdZE_wemLCaMiqlBfpUX5hH4WvDTFFQIuxjNOK5Ig4Lgkjw0-OOjO48oQW-CohXj4rTUxXZ6ZihFQK6B6B-IA5c01o2uSzBk5Mvyg1X2NNXPBCCDNC0xV_CAArlM0lKY8OO71D83RMPg9_2NTNxGSHWD_SI73Jmd9qG5YtBdZddoJIs6Asc7v0ADNU5CuBBgrCbtBRlgL-JiOqdtvb9PmQf9btUe2cKSAfqmJzsJkvxoU9dy9yzo_2pHKyV2DaRDpjP--M0BZPPEQmj0Ib2aDLES2Fs505vahQJfzuM_DMTyF0_yZb1dEYXYb4K28KfJGseEg07G5IeMG3o2lh0Pbh97rVhdPNAI2D6HnTr_WYW60FWlT_vbwFJbhhFkUfj-of277C1FdQ6XzPIjWGsHIYvMXryDifb0Ky_JqhY3ISkG7huY2qqlBkAcDWoF5V2bHdtmKimwSqNaizrrgToiyUsM8uLkMbGDdv6vmOC7yK63J7sp_eReWK_skSfIyp3wcvnubperG_37OHQDAfGrHIBD670A8qmAajaqh6QZbS-jCqSliApt5mQzDbFKfS1VeWfzciV_lbUmjS-f94FVKMGmgMHMIVCBZacYw_IvqOf6NOHypBSryyRyXeaNAZ0JMjg9z2zR9Y7YadKpa0JRtmIvF-8jlzAIMJvCJjOYjc7Byn7mJ8BdHpX2uLTYVakaLT1uXEBaifp3JVLV-CP3MsswnEEUhFwJa4E6OWBPeA






GET {{TicketSystem.API_HostAddress}}/api/ticket

###

POST {{TicketSystem.API_HostAddress}}/api/status
Content-Type: application/json

{
  "StatusName": "NewStatus"
}

###

GET {{TicketSystem.API_HostAddress}}/api/status

###

POST {{TicketSystem.API_HostAddress}}/api/tickets
Content-Type: application/json

{
  "title": "Example Ticket Title",
  "description": "Example Ticket Description"
}


###

GET {{TicketSystem.API_HostAddress}}/api/tickets
Authorization: Bearer {{token}}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/152

###


PUT {{TicketSystem.API_HostAddress}}/api/tickets/1/status
Content-Type: application/json

1234

###

PATCH {{TicketSystem.API_HostAddress}}/api/tickets/3
Content-Type: application/json

{

}

###

DELETE {{TicketSystem.API_HostAddress}}/api/tickets/12
Authorization: Bearer {{token}}

###

POST {{TicketSystem.API_HostAddress}}/api/tickets/4/comments
Content-Type: application/json

{
  "content": "Twój komentarz tutaj 2"
}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/555/comments

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/4/comments/4

###


DELETE {{TicketSystem.API_HostAddress}}/api/tickets/6/comments/5

###

POST {{TicketSystem.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

###

POST {{TicketSystem.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}