@TicketSystem.API_HostAddress = https://localhost:7013
@token = CfDJ8ET3kv6KW-NArwbm-mk0POZVa6TDwe9r_UzmiSjA0YwsqbV_wtLtiQ_uziCRDO4SJwjmPxeid7--mjdWGgeXHmQ-zL_8P-InLVQYlTcPTjEyvBDf2MVL3O27adv978J2ECAvh8JKhCQOrkqvFVVLGkLso8x-cTBAI-z3s63d0dmGCT9Z3JwFvD29FCadqUDfQgBuHMOP7O9DVlJT4ShyRLDpGOo3Yp1xrQnEXXsokovsD9gKXdxWSg6Z7qipkpTD5NxQc66O8nHl8kkStvcWA_6Jw_uPblJhHs0fid_NZh2gpPmAY6S9OFT0cYQO0S1LDv5oYUysUFDulXKwPKcAPQI6Cx7QLyfEPxXUN_mLbCltfBWn8DyPrDv2HnT9UMpVIPrwh2t5QZkh0APnDX9hlDikf0jEpYlLOfNuci01A9O5y2uIWrs8R7JxSnx7z4a_hZDLvZa_cUWQWc-MnHDhoPjk9jxCtPXzGxYHRxgLe1tFY3L7VmwsixJe41ylUdUVW1yiSvSixX9_b8dFXN8vw7K9asKIJu1OWsgg-Plj_fV9yodMSgt84odJgqM2Of6e273mvcJ7RZEZ1ZG8IX2VH6qp6kZoOzEVr2wpjjjGilWsiSplIB8k0egwv5Zm71r5kr5wtuDhluhy2dpM3pB9WzvImVXP8NzuMjnZ99gGdGKCEQGZKtGZg5N4dgbjodZFHnojon-3AvgoUxAApT7LtOPClWWqFQgJSVfeW43k5P_Meuq8w95h8nztW43oCgIRmglHfr_ak3573k_zjS2vZiu6SSKutVeofV1OYFIP4t43




GET {{TicketSystem.API_HostAddress}}/api/ticket

###

POST {{TicketSystem.API_HostAddress}}/api/status
Content-Type: application/json

{
  "StatusName": "NewStatus"
}

###

GET {{TicketSystem.API_HostAddress}}/api/status

###

POST {{TicketSystem.API_HostAddress}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example Ticket Title",
  "description": "Example Ticket Description"
}


###

GET {{TicketSystem.API_HostAddress}}/api/tickets
Authorization: Bearer {{token}}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/152

###


PUT {{TicketSystem.API_HostAddress}}/api/tickets/1/status
Content-Type: application/json

1234

###

PATCH {{TicketSystem.API_HostAddress}}/api/tickets/3
Content-Type: application/json

{

}

###

DELETE {{TicketSystem.API_HostAddress}}/api/tickets/12
Authorization: Bearer {{token}}

###

POST {{TicketSystem.API_HostAddress}}/api/tickets/4/comments
Content-Type: application/json

{
  "content": "Twój komentarz tutaj 2"
}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/555/comments

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/4/comments/4

###


DELETE {{TicketSystem.API_HostAddress}}/api/tickets/6/comments/5

###

POST {{TicketSystem.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

###

POST {{TicketSystem.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

### 

POST {{TicketSystem.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userId": "5baa6268-e6b6-4060-a03e-e3a0c7e5c315",
  "role": "Manager"
}

###


GET {{TicketSystem.API_HostAddress}}/api/identity/users
Authorization: Bearer {{token}}
###
