@TicketSystem.API_HostAddress = https://localhost:7013
@token = CfDJ8ET3kv6KW-NArwbm-mk0POZNP2KNbO9g9r3a5v7-EIQX7CnBPG6CGFfKI1lNkHLLprcdfm6SFjqeiS-2oshDXA5_UXzx41TTX5wOhlfJbM4ub-wYooYGZu1oU7xoUyGyXDF8YgvrlldWB0okecueA2UiGnBQQ0Q6X4JeWn3FsQ-M_4UORgJi3OarNsP86gvN7y_5KJmI4TNVz50zhoSgGlqGNMA5iHymELaj-mbLjfzPsCg_r0CGWuSjk34AXksbFV8jgANH8Auqw2IcV5jF8QsVOcpg-A-BCnyAZZ2jModO4vVFcJQwQwP6w2HjFeuQkYSefvNqkEIUgaQxk9dzJBIAvf5dh8VHPxR5UD-1hV9J9d-0Dl6udyJRUv8-Q7vr4UqSFBoM1mhXsmqH3R6CYM5E1Id0r4EypRDBowa1n9DUXYy3QXgsgSvV3yURanNzAwS2vOq8PBqnCsUvkZWA_VggO0CgZu_ll9fRcDlbwYJKyTCrO13Ame-_qLixQP5QfWeIUrSkxQGmyzwgTMYlzqCQskVUPnfvV9Gmo2fWNYk6-09VJNHM1BKhDQ0TsufQo-8Ry0oxDzXsLn4c6VuliAxAGvLe3AtS9sBcR0wVMk7j4RF4dUt1klSl6DoqayYcPGGpEI5tX4UESrWgIFHsh6TmZPiYLMwdjZ8FonB9Vn8qUkAnmTdIGX_x17tu0KcqMw


GET {{TicketSystem.API_HostAddress}}/api/ticket

###

POST {{TicketSystem.API_HostAddress}}/api/status
Content-Type: application/json

{
  "StatusName": "NewStatus"
}

###

GET {{TicketSystem.API_HostAddress}}/api/status

###

POST {{TicketSystem.API_HostAddress}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example Ticket Title",
  "description": "Example Ticket Description"
}


###

GET {{TicketSystem.API_HostAddress}}/api/tickets
Authorization: Bearer {{token}}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/152

###


PUT {{TicketSystem.API_HostAddress}}/api/tickets/1/status
Content-Type: application/json
Authorization: Bearer {{token}}

12

###

PATCH {{TicketSystem.API_HostAddress}}/api/tickets/3
Content-Type: application/json

{

}

###

DELETE {{TicketSystem.API_HostAddress}}/api/tickets/12
Authorization: Bearer {{token}}

###

POST {{TicketSystem.API_HostAddress}}/api/tickets/4/comments
Content-Type: application/json

{
  "content": "Twój komentarz tutaj 2"
}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/555/comments

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/4/comments/4

###


DELETE {{TicketSystem.API_HostAddress}}/api/tickets/6/comments/5

###

POST {{TicketSystem.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

###

POST {{TicketSystem.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "mateo@test.com",
    "password": "Password1!"
}

### 

POST {{TicketSystem.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userId": "5baa6268-e6b6-4060-a03e-e3a0c7e5c315",
  "role": "Manager"
}

###


GET {{TicketSystem.API_HostAddress}}/api/identity/users
Authorization: Bearer {{token}}
###
