@TicketSystem.API_HostAddress = https://localhost:7013
@token = CfDJ8ET3kv6KW-NArwbm-mk0POYqDPxHz2vjO27Z-6R-h8S4Z3x95kGFfL-Ej5sI-2caT-MwcGyru7c855aFB6362JNDZzmVW9lT1hWZRQ5tre0RrBmTICdlb3StRsLUQtfPkJ5JPB7qYR6qbzF8g-6kx8sO0Zw2pxZaoPnIHasbqGR9B_TZkXhWZ0iOKq0SWssuSNsmASDDUz1AcDThjXGlZ8oTrFmzLr0gba3P7wf-h0LP1nnGUVxoCt-7hlmG48-67SkTzyOgCAP77wh_exGkOvcI1Go5qHAEmwM8jWJwAWEPjb4S-_gkK_xH3M-fFrcFvGJvHTBL_THjbQfMMLTwI4xjzC3H8D5u723LUx8aPNBi1YLf4GP4J4cRp8p4ZcCWY_6O1RjhXxDEt5l7bsQlrxTbPMZ4yJJ8Dq_XXCJtFVh07NttS9RFF95_gr4-8SoKoTBcnc57zWx-k4Du2Wnx07BB5lFTsIOKESSgtinqIQe9iT9roT1OKFL9CoHmnWJ9hayxUHb2n0e9o0trdVChE0w5OZnrIciVeMiiTMTEbE8Ep6aXi6ZPpSBldB_48WSsJYY0cTMc-mMsOBZN7pNXIRSV8S9WPptYDFnsNBCbgBROOZ_sU1C297JHiEfZJUDib3knsJ6bj6P4IuEjnCOJYwlXPIPLjUyZLJcdwKfb6oDlMCIm8sfjav_Kax1vthsFTZPFFYQ8D5hkzqoFWS6lrxRJLzL3ez9zS1aHFkZbBltZBp9UOBa818jsP1ojMD60HcN_hV_nJULHwiPqpKq9CCXVqKtv1-nW180XVeeL2Owb



GET {{TicketSystem.API_HostAddress}}/api/ticket

###

POST {{TicketSystem.API_HostAddress}}/api/status
Content-Type: application/json

{
  "StatusName": "NewStatus"
}

###

GET {{TicketSystem.API_HostAddress}}/api/status

###

POST {{TicketSystem.API_HostAddress}}/api/tickets
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Example Ticket Title",
  "description": "Example Ticket Description"
}


###

GET {{TicketSystem.API_HostAddress}}/api/tickets
Authorization: Bearer {{token}}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/152

###


PUT {{TicketSystem.API_HostAddress}}/api/tickets/1/status
Content-Type: application/json
Authorization: Bearer {{token}}

12

###

PATCH {{TicketSystem.API_HostAddress}}/api/tickets/3
Content-Type: application/json

{

}

###

DELETE {{TicketSystem.API_HostAddress}}/api/tickets/12
Authorization: Bearer {{token}}

###

POST {{TicketSystem.API_HostAddress}}/api/tickets/4/comments
Content-Type: application/json

{
  "content": "Twój komentarz tutaj 2"
}

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/555/comments

###

GET {{TicketSystem.API_HostAddress}}/api/tickets/4/comments/4

###


DELETE {{TicketSystem.API_HostAddress}}/api/tickets/6/comments/5

###

POST {{TicketSystem.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

###

POST {{TicketSystem.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Password1!"
}

### 

POST {{TicketSystem.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userId": "5baa6268-e6b6-4060-a03e-e3a0c7e5c315",
  "role": "Manager"
}

###


GET {{TicketSystem.API_HostAddress}}/api/identity/users
Authorization: Bearer {{token}}
###
